apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Rag Bot 
  description: template to make chat bots

spec:
  type: website
  lifecycle: experimental
  owner: ${{values.owner | dump}}